### ISSUE TITLE
System variable not getting update from TOML config file

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1054]
**Description:**
System variable can be given to the micro-integrator through the TOML config file by using following parameter.
```toml
[system.parameter]
'org.wso2.SecureVaultPasswordRegEx' = "^[\\\\S]{5,60}$"
```
This is not working since default.json file replace default value with full parameter object.

**Work arround**
System parameters can be pass to the environment by using `-D` option in server startup. As an example for above case add
`-Dorg.wso2.SecureVaultPasswordRegEx=^[\\S]{5,60}$` option in server startup
