### ISSUE TITLE
Secured protocol cannot be configured to http transport sender in toml file

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1059]
**Description:**
Currently, the secured protocol can be only configured for Http transport listeners. It does not support for Http transport sender. 

The following workaround can be used as a temporary fix.

```toml
[transport.http]
sender.parameter.HttpsProtocols = "TLSv1,TLSv1.1,TLSv1.2"
```
