### ISSUE TITLE
Missing OAuth2 Token Validation  service config in deployment.toml

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1062]
**Description:**
Following configs in axis2.xml file are missing in deployment.toml.

```
<!-- OAuth2 Token Validation Service -->
<parameter name="oauth2TokenValidationService">https://localhost:9444/services/OAuth2TokenValidationService</parameter>
<!-- Server credentials -->
<parameter name="identityServerUserName">admin</parameter>
<parameter name="identityServerPw">admin</parameter>

```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madushadhanushka** [comment]
Work around

```toml
[[transport.parameters]]
name = "oauth2TokenValidationService"
value = "https://localhost:9444/services/OAuth2TokenValidationService"

[[transport.parameters]]
name = "identityServerUserName"
value = "admin"

[[transport.parameters]]
name = "identityServerPw"
value = "admin"
```

**Comment by madushadhanushka** [comment]
Following parameters will be added to configure these parameters.
```toml
[server]
auth2_token_validation_service = "https://localhost:9444/services/OAuth2TokenValidationService"
identity_server_username = "admin"
identity_server_password = "admin"
```
Following configuration added to configure axis2 parameters.
```toml
[axis2_transport]
parameters.customParameter = "value"
```
