### ISSUE TITLE
Unable to access apis when cors enabled.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1650]
**Description:**
After adding below configs to toml 

```toml

[synapse_properties]
'synapse.rest.CORSConfig.enabled' = "true"
'synapse.rest.CORSConfig.Access-Control-Allow-Origin' = "*"
'synapse.rest.CORSConfig.Access-Control-Allow-Headers' = "content-type"
```

invoking the api gives the following error.

```bash

[2020-06-10 14:10:51,898]  WARN {FaultHandler} - {api:TestAPI} ERROR_CODE : 0 ERROR_MESSAGE : Provided origin URL * is malformed
[2020-06-10 14:10:51,985]  INFO {LogMediator} - {api:TestAPI} To: /original, MessageID: urn:uuid:b9a1789a-5499-401c-8412-74e383af08ab, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Provided origin URL * is malformed, Payload: {"sa":"sa"}

```
