### ISSUE TITLE
Unable to do authorization with LDAP (  read_write or read_only) user store 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1802]
After login to the dashboard , try to list the users with it. Following error will be printed in console

```bash
[2020-07-07 13:01:00,012] ERROR {AuthorizationHandler} - User admin cannot be authorized
```
Toml configs
```toml
[user_store]
type = "read_write_ldap"
connection_url = "ldap://localhost:10396"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
user_search_base = "ou=Users,dc=wso2,dc=org"

[[management_api.authorization_handler.resources]]
path = "/user"
```

Here the retrieved role is only listed as internal/everyone in https://github.com/wso2/micro-integrator/blob/master/components/org.wso2.micro.integrator.extensions/org.wso2.micro.integrator.management.apis/src/main/java/org/wso2/micro/integrator/management/apis/security/handler/AuthorizationHandler.java#L109
