### ISSUE TITLE
Analytics monitoring configurations are not supported by TOML configs

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1970]
Analytics monitoring configurations in carbon.xml file do not support the TOML configurations in MI 1.1.0 product. The sample configurations will be as follows.

```toml
[monitoring]
jmx.rmi_registry_port=9999 
jmx.rmi_server_port=11111
jmx.rmi_server_start=true 
jmx.rmi_hostname="$ref{server.hostname}" 

ei_analytics.server_url = "tcp://localhost:7612"
ei_analytics.auth_server_url = "ssl://localhost:7712"
ei_analytics.username = "admin"
ei_analytics.password = "admin"
```
