### ISSUE TITLE
Incorrect configuration in integration_controller_conf.yaml

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#2133]
**Description:**
The integration_controller_conf file has incorrect configuration which leads to incorrect request routing (comma should be removed).
Existing one
```
data:
  ingress.properties: |
    kubernetes.io/ingress.class: nginx
    **nginx.ingress.kubernetes.io/rewrite-target: /$2,**
    nginx.ingress.kubernetes.io/ssl-redirect: false
  ingressResourceName: "api-operator-ingress"
```

Corrected one
```
data:
  ingress.properties: |
    kubernetes.io/ingress.class: nginx
    **nginx.ingress.kubernetes.io/rewrite-target: /$2**
    nginx.ingress.kubernetes.io/ssl-redirect: false
  ingressResourceName: "api-operator-ingress"
```
