### ISSUE TITLE
How to point out the WSO2 MI from MI-DASHBOARD in version 4.0.0 on containers

### ISSUE THREAD

**Issue by serrodcal** [wso2/micro-integrator#2290]
**Description:**
Starting WSO2 MI 4.0.0 and MI-DASHBOARD 4.0.0 together in a docker compose, after browse http://localhost:9743 and set the credentials, the dashboard cannot connect to the MI Server printing the following error: 

```
dashboard         | [2021-05-13 11:41:01,891] ERROR {LoginDelegate} - No running micro integrator instances found. Please start a server and login.
```

Is there any environment variable to be able to set the proper value on containers?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** WSO2 MI 4.0.0 and WSO2 MI-DASHBOARD 4.0.0

**OS, DB, other environment details and versions:**    MacOs Catalina

**Steps to reproduce:**

From the following `docker-compose.yml` file:

```yml
version: '3.8'

networks:
  local:

services:
  micro-integrator:
    container_name: "micro-integrator"
    image: wso2/wso2mi:4.0.0
    ports:
      - "8290:8290"
      - "8253:8253"
      - "9164:9164"
    #environment:
    #  - JAVA_OPTS="-DenablePrometheusApi=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=0.0.0.0"
    volumes:
      - ./api/Echo.xml:/home/wso2carbon/wso2mi-4.0.0/repository/deployment/server/synapse-configs/default/api/Echo.xml
      - ./api/Hello.xml:/home/wso2carbon/wso2mi-4.0.0/repository/deployment/server/synapse-configs/default/api/Hello.xml
    networks:
      - local
  dashboard:
    container_name: "dashboard"
    image: wso2/wso2mi-dashboard:4.0.0
    ports:
      - "9743:9743"
    environment:
      - DASHBOARD_CONFIG_URL=http://micro-integrator:9164
    networks:
      - local
    depends_on:
      - micro-integrator
```

Start both products:

```shell
$ docker compose up
```

Then, go to [https://localhost:9743/login](https://localhost:9743/login).

**Related Issues:**
