### ISSUE TITLE
RabbitMQ Exchage declaration fails when there is already an exchange with extra paramters

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#2376]
**Description:**
$subject

**Affected Product Version:**
MI-1.2.0

**Steps to reproduce:**

1. Configure RabbitMQ AMQP with Micro Integrator.
2. Add the following configurations to deployment.toml file.

```toml
[transport.rabbitmq]
 sender_enable = true
 listener_enable = true

 [[transport.rabbitmq.sender]]
 name = "AMQPConnectionFactory"
 parameter.port = 5673
 parameter.username = "guest"
 parameter.password = "guest"


 [[transport.rabbitmq.listener]]
 name = "AMQPConnectionFactory"
 parameter.hostname = "localhost"
 parameter.port = 5673
 parameter.username = "guest"
 parameter.password = "guest"
 parameter.retry_interval = "10"
parameter.retry_count = 5  
```
4. Create a exchange with an alternate-exchange property.
3. Use the proxy RabbitProxy.xml to publish messages to the queue.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="RabbitProxy"
       transports="http https"
       startOnLoad="true">
   <description/>
   <target>
      <inSequence>
         <property name="OUT_ONLY" value="true" scope="default" type="STRING"/>
        <log level="custom" category="INFO">
            <property name="this log is" value="***proxy invoked***"/>
         </log>
         <call>
            <endpoint>
               <address uri="rabbitmq:/?rabbitmq.server.host.name=localhost&amp;rabbitmq.server.user.name=guest&amp;rabbitmq.server.password=guest&amp;rabbitmq.server.port=5672&amp;rabbitmq.queue.name=testQ&amp;rabbitmq.exchange.autodeclare=false&amp;rabbitmq.queue.autodeclare=false&amp;rabbitmq.exchange.name=hasi&amp;rabbitmq.connection.factory=CachedRabbitMQConnectionFactory&amp;rabbitmq.queue.route.key=testK"/>
            </endpoint>
         </call>
         <respond/>
      </inSequence>
   </target>
</proxy>
```
