### ISSUE TITLE
Cannot create a new super admin user

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/micro-integrator#2648]
**Description:**
When we use a JDBC user store and try to add a superuser using the following config, the newly created user will be a non-admin user if there is a super admin user already present in the user store. But if we try the same in EI 660, it will create a new super admin user.

```toml
[super_admin]
username = "admin2"
password = "admin2"
admin_role = "admin"
create_admin_account = true
```

**Steps to reproduce:**
1. Configure a [JDBC user store](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore/)
2. Start the MI pack without adding the `super_admin` element to the toml. This will create a super admin user as `admin`.
3. Add the above `super_admin` element to the toml and restart the server.
4. If you login to the dashboard and check, the newly created super admin user `admin2` will be a non admin user.
5. If we check the user store database, it doesn't have the admin role assigned to the new user `admin2`.
